### ISSUE TITLE
[question] supported caching providers in main branch

### ISSUE THREAD

**Issue by yongzhang** [darkweak/souin#215]
Hi, 

I want use redis as caching provider, but I'm a bit confused about supported caching providers in the main branch, 

From the documentation below, `It provides an in-memory, redis and Olric cache systems because setting, getting, updating and deleting keys in these providers is as easy as it gets`, so does it support redis?

```
Cache systems
Supported providers

[Badger](https://github.com/dgraph-io/badger)
[Olric](https://github.com/buraksezer/olric)
The cache system sits on top of three providers at the moment. It provides an in-memory, redis and Olric cache systems because setting, getting, updating and deleting keys in these providers is as easy as it gets.
In order to do that, the [Olric](https://github.com/buraksezer/olric) provider need to be either on the same network as the Souin instance when using docker-compose or over the internet, then it will use by default in-memory to avoid network latency as much as possible. Souin will return at first the in-memory response when it gives a non-empty response, then the olric one followed by the redis one with same condition, or fallback to the reverse proxy otherwise. Since v1.4.2, Souin supports Olric to handle distributed cache.
```

And in the beginning of the docs, looks like redis is only supported in https://github.com/Darkweak/Souin/tree/full-version, but in that branch, seems code is not maintained anymore?

**Comment by darkweak** [comment]
You're right, redis is not supported on the master branch because it's too slow compared to olric and badger. I plan to move from badger to lotusdb in the next release BTW to patch this issue https://github.com/caddyserver/cache-handler/issues/27.  
The full-version branch is not maintained anymore because there was too many changes and was not really used so it was time wasting for me.
I'll fix the documentation in the PR with the lotusdb introduction.

**Comment by yongzhang** [comment]
if I define below block only, it will do in-memory caching right?
```
default_cache: # Required
  ttl: 10s # Default TTL
```

**Comment by darkweak** [comment]
Yes it does

**Comment by ueffel** [comment]
> I plan to move from badger to lotusdb in the next release BTW to patch this issue [caddyserver/cache-handler#27](https://github.com/caddyserver/cache-handler/issues/27).

I like the move away from badger. I'm trying to use the caddy cache-handler on my raspberry pi, but [apparently badger isn't compatible arm](https://discuss.dgraph.io/t/error-mremap-size-mismatch-on-arm64/15333). Maybe lotusdb works better :)

**Comment by darkweak** [comment]
It should be okay once this branch got merged https://github.com/darkweak/souin/tree/feat/plugins/introduce-beego-plugin. I'm grouping commits for enhancements in this branch.

**Comment by darkweak** [comment]
Update: First I'll keep badger as the default provider and set nutsdb as the default one when I'll tag the v1.7.0

**Comment by ueffel** [comment]
hi there

I tried to use the new nutsdb provider with caddy and so I build caddy with

```
github.com/darkweak/souin/plugins/caddy v0.0.0-20220616183608-602a4e16d6cc
github.com/darkweak/souin       v1.6.9 
```

on arm it works fine, but on windows and I keep getting the following panic, if some cache key should be save into nutsdb


```
http.stdlib     http: panic serving [::1]:1946: Impossible to set value into Nuts, FlushFileBuffers: Das Handle ist ungültig.
goroutine 165 [running]:
net/http.(*conn).serve.func1()
        net/http/server.go:1825 +0xbf
panic({0x2535260, 0xc000440640})
        runtime/panic.go:844 +0x258
github.com/darkweak/souin/cache/providers.(*Nuts).Set(0xc0001098c0, {0xc00003e640, 0x1c}, {0xc00016c480, 0xd2, 0x42c}, {{0x2540be400}, {0x3a96928, 0x0, 0x0}, ...}, ...)
        github.com/darkweak/souin@v1.6.9/cache/providers/nutsProvider.go:125 +0x239
github.com/darkweak/souin/rfc.(*VaryTransport).SetCache(0xc0000060c0, {0xc00003e640, 0x1c}, 0xc0001a6630)
        github.com/darkweak/souin@v1.6.9/rfc/transport.go:85 +0x263
github.com/darkweak/souin/rfc.validateVary.func1({0x2bf6040, 0xc0000f4de0})
        github.com/darkweak/souin@v1.6.9/rfc/vary.go:37 +0x125
github.com/darkweak/souin/rfc.(*cachingReadCloser).Read(0xc0004c7a40, {0xc0008be040, 0x1bd33171470?, 0x1c0})
        github.com/darkweak/souin@v1.6.9/rfc/standalone.go:352 +0x177
io.ReadAll({0x1bd33171470, 0xc0004c7a40})
        io/io.go:645 +0xfe
io/ioutil.ReadAll(...)
        io/ioutil/ioutil.go:27
github.com/darkweak/souin/plugins.(*CustomWriter).Send(0xc0005a8480)
        github.com/darkweak/souin@v1.6.9/plugins/base.go:68 +0x20f
github.com/darkweak/souin/plugins/caddy.(*SouinCaddyPlugin).ServeHTTP.func1({0x25bf7a0?, 0x2531720?}, 0x28aa9b7?)
        github.com/darkweak/souin/plugins/caddy@v0.0.0-20220616183608-602a4e16d6cc/httpcache.go:125 +0x10f
github.com/darkweak/souin/plugins.DefaultSouinPluginCallback({0x2c04330, 0xc0005a8480}, 0xc0002e8800, {0x2c13258, 0xc0000a8360}, {0x0, 0x0}, 0xc00009c410)
        github.com/darkweak/souin@v1.6.9/plugins/base.go:178 +0x6df
github.com/darkweak/souin/plugins/caddy.(*SouinCaddyPlugin).ServeHTTP(0xc00020e3c0, {0x1bd3316fa50?, 0xc0005a69f0}, 0xc0002e8300, {0x2bfc660, 0xc0005a8420})
        github.com/darkweak/souin/plugins/caddy@v0.0.0-20220616183608-602a4e16d6cc/httpcache.go:113 +0x7cc
github.com/caddyserver/caddy/v2/modules/caddyhttp.(*metricsInstrumentedHandler).ServeHTTP(0xc0005a8080, {0x1bd3316fa50?, 0xc0005a68a0}, 0xc0002e8300, {0x2bfc660, 0xc0005a8420})
        github.com/caddyserver/caddy/v2@v2.5.1/modules/caddyhttp/metrics.go:132 +0x53b
github.com/caddyserver/caddy/v2/modules/caddyhttp.wrapMiddleware.func1.1({0x1bd3316fa50?, 0xc0005a68a0?}, 0x2bfc660?)
        github.com/caddyserver/caddy/v2@v2.5.1/modules/caddyhttp/routes.go:272 +0x3b
github.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0x2bfc660?, {0x1bd3316fa50?, 0xc0005a68a0?}, 0x0?)
        github.com/caddyserver/caddy/v2@v2.5.1/modules/caddyhttp/caddyhttp.go:57 +0x2f
github.com/caddyserver/caddy/v2/modules/caddyhttp.wrapRoute.func1.1({0x1bd3316fa50, 0xc0005a68a0}, 0xc0002e8300)
        github.com/caddyserver/caddy/v2@v2.5.1/modules/caddyhttp/routes.go:244 +0x322
github.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0xc0000cab40?, {0x1bd3316fa50?, 0xc0005a68a0?}, 0x2bfc660?)
        github.com/caddyserver/caddy/v2@v2.5.1/modules/caddyhttp/caddyhttp.go:57 +0x2f
github.com/caddyserver/caddy/v2/modules/caddyhttp.(*Subroute).ServeHTTP(0xc0006290c0, {0x1bd3316fa50, 0xc0005a68a0}, 0x6?, {0x2bfc660, 0x2946638})
        github.com/caddyserver/caddy/v2@v2.5.1/modules/caddyhttp/subroute.go:74 +0x6d
github.com/caddyserver/caddy/v2/modules/caddyhttp.(*metricsInstrumentedHandler).ServeHTTP(0xc0005a80c0, {0x1bd3316fa50?, 0xc0005a6750}, 0xc0002e8300, {0x2bfc660, 0x2946638})
        github.com/caddyserver/caddy/v2@v2.5.1/modules/caddyhttp/metrics.go:132 +0x53b
github.com/caddyserver/caddy/v2/modules/caddyhttp.wrapMiddleware.func1.1({0x1bd3316fa50?, 0xc0005a6750?}, 0x2bfc660?)
        github.com/caddyserver/caddy/v2@v2.5.1/modules/caddyhttp/routes.go:272 +0x3b
github.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0x2bfc660?, {0x1bd3316fa50?, 0xc0005a6750?}, 0xfd4bc6?)
        github.com/caddyserver/caddy/v2@v2.5.1/modules/caddyhttp/caddyhttp.go:57 +0x2f
github.com/caddyserver/caddy/v2/modules/caddyhttp.wrapRoute.func1.1({0x1bd3316fa50, 0xc0005a6750}, 0xc0002e8300)
        github.com/caddyserver/caddy/v2@v2.5.1/modules/caddyhttp/routes.go:244 +0x322
github.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0xc0000c0f90?, {0x1bd3316fa50?, 0xc0005a6750?}, 0x4?)
        github.com/caddyserver/caddy/v2@v2.5.1/modules/caddyhttp/caddyhttp.go:57 +0x2f
github.com/caddyserver/caddy/v2/modules/caddyhttp.VarsMiddleware.ServeHTTP(0x1bd3316fa50?, {0x1bd3316fa50, 0xc0005a6750}, 0xc0002e8300, {0x2bfc660, 0xc0005a80e0})
        github.com/caddyserver/caddy/v2@v2.5.1/modules/caddyhttp/vars.go:60 +0x273
github.com/caddyserver/caddy/v2/modules/caddyhttp.(*metricsInstrumentedHandler).ServeHTTP(0xc000628f60, {0x2c07420?, 0xc00002a000}, 0xc0002e8300, {0x2bfc660, 0xc0005a80e0})
        github.com/caddyserver/caddy/v2@v2.5.1/modules/caddyhttp/metrics.go:132 +0x53b
github.com/caddyserver/caddy/v2/modules/caddyhttp.wrapMiddleware.func1.1({0x2c07420?, 0xc00002a000?}, 0x2bfc660?)
        github.com/caddyserver/caddy/v2@v2.5.1/modules/caddyhttp/routes.go:272 +0x3b
github.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0x2bfc660?, {0x2c07420?, 0xc00002a000?}, 0x0?)
        github.com/caddyserver/caddy/v2@v2.5.1/modules/caddyhttp/caddyhttp.go:57 +0x2f
github.com/caddyserver/caddy/v2/modules/caddyhttp.wrapRoute.func1.1({0x2c07420, 0xc00002a000}, 0xc0002e8300)
        github.com/caddyserver/caddy/v2@v2.5.1/modules/caddyhttp/routes.go:244 +0x322
github.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0xc000177400?, {0x2c07420?, 0xc00002a000?}, 0x277f2a0?)
        github.com/caddyserver/caddy/v2@v2.5.1/modules/caddyhttp/caddyhttp.go:57 +0x2f
github.com/caddyserver/caddy/v2/modules/caddyhttp.(*Server).enforcementHandler(0x0?, {0x2c07420?, 0xc00002a000?}, 0xc0006fa4c0?, {0x2bfc660?, 0xc0005a8100?})
        github.com/caddyserver/caddy/v2@v2.5.1/modules/caddyhttp/server.go:318 +0x252
github.com/caddyserver/caddy/v2/modules/caddyhttp.(*Server).wrapPrimaryRoute.func1({0x2c07420?, 0xc00002a000?}, 0xfc8637?)
        github.com/caddyserver/caddy/v2@v2.5.1/modules/caddyhttp/server.go:294 +0x3b
github.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0xc00016f8c0?, {0x2c07420?, 0xc00002a000?}, 0xc0002e8300?)
        github.com/caddyserver/caddy/v2@v2.5.1/modules/caddyhttp/caddyhttp.go:57 +0x2f
github.com/caddyserver/caddy/v2/modules/caddyhttp.(*Server).ServeHTTP(0xc0000fe240, {0x2c07420, 0xc00002a000}, 0xc0002e8300)
        github.com/caddyserver/caddy/v2@v2.5.1/modules/caddyhttp/server.go:230 +0xac6
net/http.serverHandler.ServeHTTP({0xc0005a6390?}, {0x2c07420, 0xc00002a000}, 0xc0002e8100)
        net/http/server.go:2916 +0x43b
net/http.(*conn).serve(0xc0001b2960, {0x2c09148, 0xc00034df80})
        net/http/server.go:1966 +0x5d7
created by net/http.(*Server).Serve
        net/http/server.go:3071 +0x4db
```

its an `*os.SyscallError {Syscall: "FlushFileBuffers", Err: error(syscall.Errno) golang.org/x/sys/windows.ERROR_INVALID_HANDLE (6)}` error.



```caddy-d
{
	debug
	order cache before rewrite
	cache {
		nuts {
			path cache
		}
	}
}

http://:80 {
	root .
	handle /cachable/* {
		cache {
			ttl 10s
		}
		reverse_proxy 127.0.0.1:8080
	}
}

http://:8080 {
	respond "Hello, your visited {uri} at {time.now.common_log}"
}
```

```shell
$ curl http://localhost/cachable/hi
curl: (52) Empty reply from server
```

Any idea whats happening?

**Comment by darkweak** [comment]
Can you try with custom options and disable the SyncEnable property https://github.com/nutsdb/nutsdb

Note that the windows FS is a pain
https://github.com/dgraph-io/badger/issues/699

**Comment by ueffel** [comment]
> Can you try with custom options and disable the SyncEnable property https://github.com/nutsdb/nutsdb

It helps for the first few requests but I guess it has to flush to disk at some point and this is where is panics again.

Using

```caddy-d
	cache {
		nuts {
			path cache
			configuration {
			}
		}
	}
```

as config helps, because it uses the default `nutsdb.Options.RWMode` which is `nutsdb.FileIO` instead of `nutsdb.MMap` With this everything works as expected as far as I can tell.

**Comment by ueffel** [comment]
This just errors `Impossible to parse the configuration for the Nuts provider json: cannot unmarshal string into Go struct field Options.RWMode of type nutsdb.RWMode`

**Comment by darkweak** [comment]
You're right because it's a iota. I'll setup the parser tonight.
