### ISSUE TITLE
panic when using local plugin mode

### ISSUE THREAD

**Issue by yongzhang** [darkweak/souin#216]
traefik version: v2.6.7
souin version: v1.6.8
Reference: https://traefik.io/blog/using-private-plugins-in-traefik-proxy-2-5/

Dockerfile:
```
FROM golang:1.18
ENV PLUGIN_MODULE=github.com/darkweak/souin
ENV PLUGIN_GIT_REPO=https://github.com/darkweak/souin.git
ENV PLUGIN_GIT_BRANCH=v1.6.8
RUN git clone ${PLUGIN_GIT_REPO} /plugins-local/src/${PLUGIN_MODULE} \
      --depth 1 --single-branch --branch ${PLUGIN_GIT_BRANCH}

FROM traefik:v2.6.7
COPY --from=0 /plugins-local /plugins-local
```

traefik static config:
```
    [entryPoints]
      ...
      [entryPoints.web]
        address = ":80"
        [entryPoints.web.http]
          middlewares = ["caching@file"]

    [experimental]
      [experimental.localPlugins]
        [experimental.localPlugins.souin]
          moduleName = "github.com/darkweak/souin"
```

traefik dynamic config:
```
    [http]
      [http.middlewares]
        [http.middlewares.caching]
          [http.middlewares.caching.plugin]
            [http.middlewares.caching.plugin.souin]
              [http.middlewares.caching.plugin.souin.default_cache]
                ttl = "10s"
```

Errors:
```
{"level":"error","module":"github.com/darkweak/souin","msg":"plugins-local/src/github.com/darkweak/souin/plugins/traefik/vendor/github.com/darkweak/souin/cache/surrogate/providers/common.go:132:36: panic","plugin":"plugin-souin","time":"2022-05-30T09:49:39Z"}
{"level":"error","module":"github.com/darkweak/souin","msg":"plugins-local/src/github.com/darkweak/souin/plugins/traefik/vendor/github.com/darkweak/souin/cache/surrogate/providers/common.go:143:7: panic","plugin":"plugin-souin","time":"2022-05-30T09:49:39Z"}
{"level":"error","module":"github.com/darkweak/souin","msg":"plugins-local/src/github.com/darkweak/souin/plugins/traefik/vendor/github.com/darkweak/souin/cache/surrogate/providers/souin.go:29:8: panic","plugin":"plugin-souin","time":"2022-05-30T09:49:39Z"}
{"level":"error","module":"github.com/darkweak/souin","msg":"plugins-local/src/github.com/darkweak/souin/plugins/traefik/vendor/github.com/darkweak/souin/rfc/vary.go:34:11: panic","plugin":"plugin-souin","time":"2022-05-30T09:49:39Z"}
{"level":"error","module":"github.com/darkweak/souin","msg":"plugins-local/src/github.com/darkweak/souin/plugins/traefik/vendor/github.com/darkweak/souin/rfc/standalone.go:344:5: panic","plugin":"plugin-souin","time":"2022-05-30T09:49:39Z"}
{"level":"error","module":"github.com/darkweak/souin","msg":"plugins-local/src/github.com/darkweak/souin/plugins/traefik/base.go:62:20: panic","plugin":"plugin-souin","time":"2022-05-30T09:49:39Z"}
{"level":"error","module":"github.com/darkweak/souin","msg":"plugins-local/src/github.com/darkweak/souin/plugins/traefik/main.go:260:7: panic","plugin":"plugin-souin","time":"2022-05-30T09:49:39Z"}
{"level":"error","module":"github.com/darkweak/souin","msg":"plugins-local/src/github.com/darkweak/souin/plugins/traefik/base.go:112:14: panic","plugin":"plugin-souin","time":"2022-05-30T09:49:39Z"}
{"level":"error","module":"github.com/darkweak/souin","msg":"plugins-local/src/github.com/darkweak/souin/plugins/traefik/main.go:201:8: panic","plugin":"plugin-souin","time":"2022-05-30T09:49:39Z"}
{"level":"error","middlewareName":"traefik-internal-recovery","middlewareType":"Recovery","msg":"Recovered from panic in HTTP handler [10.120.18.218:21330 - /metrics]: runtime error: invalid memory address or nil pointer dereference","time":"2022-05-30T09:49:39Z"}
{"level":"error","middlewareName":"traefik-internal-recovery","middlewareType":"Recovery","msg":"Stack: goroutine 645 [running]:\ngithub.com/traefik/traefik/v2/pkg/middlewares/recovery.recoverFunc({0x7fd0453bb170, 0xc000e7ef70}, 0xc000a51a00)\n\tgithub.com/traefik/traefik/v2/pkg/middlewares/recovery/recovery.go:46 +0x225\npanic({0x2feb9e0, 0x5df0660})\n\truntime/panic.go:1038 +0x215\ngithub.com/traefik/yaegi/interp.runCfg.func1()\n\tgithub.com/traefik/yaegi@v0.12.0/interp/run.go:192 +0x145\npanic({0x2feb9e0, 0x5df0660})\n\truntime/panic.go:1038 +0x215\ngithub.com/traefik/yaegi/interp.runCfg.func1()\n\tgithub.com/traefik/yaegi@v0.12.0/interp/run.go:192 +0x145\npanic({0x2feb9e0, 0x5df0660})\n\truntime/panic.go:1038 +0x215\ngithub.com/traefik/yaegi/interp.runCfg.func1()\n\tgithub.com/traefik/yaegi@v0.12.0/interp/run.go:192 +0x145\npanic({0x2feb9e0, 0x5df0660})\n\truntime/panic.go:1038 +0x215\ngithub.com/traefik/yaegi/interp.runCfg.func1()\n\tgithub.com/traefik/yaegi@v0.12.0/interp/run.go:192 +0x145\npanic({0x2feb9e0, 0x5df0660})\n\truntime/panic.go:1038 +0x215\ngithub.com/traefik/yaegi/interp.runCfg.func1()\n\tgithub.com/traefik/yaegi@v0.12.0/interp/run.go:192 +0x145\npanic({0x2feb9e0, 0x5df0660})\n\truntime/panic.go:1038 +0x215\ngithub.com/traefik/yaegi/interp.runCfg.func1()\n\tgithub.com/traefik/yaegi@v0.12.0/interp/run.go:192 +0x145\npanic({0x2feb9e0, 0x5df0660})\n\truntime/panic.go:1038 +0x215\ngithub.com/traefik/yaegi/interp.runCfg.func1()\n\tgithub.com/traefik/yaegi@v0.12.0/interp/run.go:192 +0x145\npanic({0x2feb9e0, 0x5df0660})\n\truntime/panic.go:1038 +0x215\ngithub.com/traefik/yaegi/interp.runCfg.func1()\n\tgithub.com/traefik/yaegi@v0.12.0/interp/run.go:192 +0x145\npanic({0x2feb9e0, 0x5df0660})\n\truntime/panic.go:1038 +0x215\ngithub.com/traefik/yaegi/interp.runCfg.func1()\n\tgithub.com/traefik/yaegi@v0.12.0/interp/run.go:192 +0x145\npanic({0x2feb9e0, 0x5df0660})\n\truntime/panic.go:1038 +0x215\ngithub.com/traefik/yaegi/interp.genFunctionWrapper(0xc006139e60)\n\tgithub.com/traefik/yaegi@v0.12.0/interp/run.go:962 +0xd6\ngithub.com/traefik/yaegi/interp.call.func9(0xc006155550)\n\tgithub.com/traefik/yaegi@v0.12.0/interp/run.go:1420 +0xcc5\ngithub.com/traefik/yaegi/interp.runCfg(0xc001bb5b00, 0xc006155550, 0x8b4f12e600000001, 0x3455ac0)\n\tgithub.com/traefik/yaegi@v0.12.0/interp/run.go:200 +0x2ac\ngithub.com/traefik/yaegi/interp.call.func9(0xc006155340)\n\tgithub.com/traefik/yaegi@v0.12.0/interp/run.go:1433 +0x94e\ngithub.com/traefik/yaegi/interp.runCfg(0xc001bba6c0, 0xc006155340, 0x0, 0x2dfd9e0)\n\tgithub.com/traefik/yaegi@v0.12.0/interp/run.go:200 +0x2ac\ngithub.com/traefik/yaegi/interp.call.func9(0xc006155130)\n\tgithub.com/traefik/yaegi@v0.12.0/interp/run.go:1433 +0x94e\ngithub.com/traefik/yaegi/interp.runCfg(0xc001df8fc0, 0xc006155130, 0x67c11f9b00000001, 0x2dfd9e0)\n\tgithub.com/traefik/yaegi@v0.12.0/interp/run.go:200 +0x2ac\ngithub.com/traefik/yaegi/interp.call.func9(0xc006154fd0)\n\tgithub.com/traefik/yaegi@v0.12.0/interp/run.go:1433 +0x94e\ngithub.com/traefik/yaegi/interp.runCfg(0xc003a6ec60, 0xc006154fd0, 0x0, 0x3058f80)\n\tgithub.com/traefik/yaegi@v0.12.0/interp/run.go:200 +0x2ac\ngithub.com/traefik/yaegi/interp.genFunctionWrapper.func2.1({0xc006149608, 0x1, 0x2})\n\tgithub.com/traefik/yaegi@v0.12.0/interp/run.go:1022 +0x4a5\nreflect.Value.call({0x2df27a0, 0xc003716190, 0xc00238dc40}, {0x363b5aa, 0x4}, {0xc0061495f0, 0x1, 0xc005b7ad58})\n\treflect/value.go:556 +0x845\nreflect.Value.Call({0x2df27a0, 0xc003716190, 0x884a1c}, {0xc0061495f0, 0x1, 0x1})\n\treflect/value.go:339 +0xc5\ngithub.com/traefik/yaegi/interp.callBin.func1({0x2df27a0, 0xc003716190, 0x4aca66}, {0xc0061495f0, 0xc00329c7e0, 0x7fd06c4f9108})\n\tgithub.com/traefik/yaegi@v0.12.0/interp/run.go:1483 +0x28\ngithub.com/traefik/yaegi/interp.callBin.func10(0xc006154dc0)\n\tgithub.com/traefik/yaegi@v0.12.0/interp/run.go:1657 +0x158\ngithub.com/traefik/yaegi/interp.runCfg(0xc003a32360, 0xc006154dc0, 0x3, 0x2d88600)\n\tgithub.com/traefik/yaegi@v0.12.0/interp/run.go:200 +0x2ac\ngithub.com/traefik/yaegi/interp.genFunctionWrapper.func2.1({0xc006149458, 0x1, 0x4})\n\tgithub.com/traefik/yaegi@v0.12.0/interp/run.go:1022 +0x4a5\ngithub.com/traefik/yaegi/stdlib._io_ReadCloser.Read(...)\n\tgithub.com/traefik/yaegi@v0.12.0/stdlib/go1_17_io.go:152\nio.ReadAll({0x7fd0453bb9c0, 0xc001de3900})\n\tio/io.go:633 +0xfe\nio/ioutil.ReadAll({0x7fd0453bb9c0, 0xc001de3900})\n\tio/ioutil/ioutil.go:27 +0x25\nreflect.Value.call({0x2f13e20, 0x3b3a928, 0x3102280}, {0x363b5aa, 0x4}, {0xc004846ae0, 0x1, 0x7fd0450d2468})\n\treflect/value.go:556 +0x845\nreflect.Value.Call({0x2f13e20, 0x3b3a928, 0x451b32}, {0xc004846ae0, 0x1, 0x1})\n\treflect/value.go:339 +0xc5\ngithub.com/traefik/yaegi/interp.callBin.func1({0x2f13e20, 0x3b3a928, 0xc00428d900}, {0xc004846ae0, 0x18, 0x2d88600})\n\tgithub.com/traefik/yaegi@v0.12.0/interp/run.go:1483 +0x28\ngithub.com/traefik/yaegi/interp.callBin.func8(0xc00613da20)\n\tgithub.com/traefik/yaegi@v0.12.0/interp/run.go:1624 +0x158\ngithub.com/traefik/yaegi/interp.runCfg(0xc000802000, 0xc00613da20, 0x0, 0xc003b36f80)\n\tgithub.com/traefik/yaegi@v0.12.0/interp/run.go:200 +0x2ac\ngithub.com/traefik/yaegi/interp.call.func9(0xc00607ce70)\n\tgithub.com/traefik/yaegi@v0.12.0/interp/run.go:1433 +0x94e\ngithub.com/traefik/yaegi/interp.runCfg(0xc003ba4120, 0xc00607ce70, 0xc005fe2218, 0x352fc20)\n\tgithub.com/traefik/yaegi@v0.12.0/interp/run.go:200 +0x2ac\ngithub.com/traefik/yaegi/interp.call.func9(0xc006076c60)\n\tgithub.com/traefik/yaegi@v0.12.0/interp/run.go:1433 +0x94e\ngithub.com/traefik/yaegi/interp.runCfg(0xc00081d320, 0xc006076c60, 0xc005fe2478, 0x343fa40)\n\tgithub.com/traefik/yaegi@v0.12.0/interp/run.go:200 +0x2ac\ngithub.com/traefik/yaegi/interp.call.func9(0xc00602ec60)\n\tgithub.com/traefik/yaegi@v0.12.0/interp/run.go:1433 +0x94e\ngithub.com/traefik/yaegi/interp.runCfg(0xc003b826c0, 0xc00602ec60, 0x39, 0x352fc20)\n\tgithub.com/traefik/yaegi@v0.12.0/interp/run.go:200 +0x2ac\ngithub.com/traefik/yaegi/interp.genFunctionWrapper.func2.1({0xc003296c00, 0x2, 0x4})\n\tgithub.com/traefik/yaegi@v0.12.0/interp/run.go:1022 +0x4a5\ngithub.com/traefik/yaegi/stdlib._net_http_Handler.ServeHTTP(...)\n\tgithub.com/traefik/yaegi@v0.12.0/stdlib/go1_17_net_http.go:288\ngithub.com/klauspost/compress/gzhttp.NewWrapper.func1.1({0x7fd0453bb170, 0xc000e7ef70}, 0xc003cc4de0)\n\tgithub.com/klauspost/compress@v1.13.0/gzhttp/gzip.go:378 +0x2d9\nnet/http.HandlerFunc.ServeHTTP(0xc000473b00, {0x7fd0453bb170, 0xc000e7ef70}, 0x0)\n\tnet/http/server.go:2047 +0x2f\ngithub.com/traefik/traefik/v2/pkg/middlewares/compress.(*compress).ServeHTTP(0xc000473b00, {0x7fd0453bb170, 0xc000e7ef70}, 0xc0013c0200)\n\tgithub.com/traefik/traefik/v2/pkg/middlewares/compress/compress.go:61 +0x1b4\ngithub.com/traefik/traefik/v2/pkg/middlewares/tracing.(*Wrapper).ServeHTTP(0xc00321a480, {0x7fd0453bb170, 0xc000e7ef70}, 0xc0013c0100)\n\tgithub.com/traefik/traefik/v2/pkg/middlewares/tracing/wrapper.go:66 +0xcc\ngithub.com/traefik/traefik/v2/pkg/middlewares/accesslog.(*FieldHandler).ServeHTTP(0xc000473b40, {0x7fd0453bb170, 0xc000e7ef70}, 0x2fa2b20)\n\tgithub.com/traefik/traefik/v2/pkg/middlewares/accesslog/field_middleware.go:38 +0xf6\ngithub.com/gorilla/mux.(*Router).ServeHTTP(0xc00305b200, {0x7fd0453bb170, 0xc000e7ef70}, 0xc000a51a00)\n\tgithub.com/gorilla/mux@v1.8.0/mux.go:141 +0x24c\ngithub.com/traefik/traefik/v2/pkg/middlewares/recovery.(*recovery).ServeHTTP(0xc003ceda68, {0x7fd0453bb170, 0xc000e7ef70}, 0x3052500)\n\tgithub.com/traefik/traefik/v2/pkg/middlewares/recovery/recovery.go:32 +0x82\ngithub.com/traefik/traefik/v2/pkg/middlewares/accesslog.AddOriginFields({0x7fd0453bb250, 0xc000e7ef68}, 0x365b9bd, {0x3f6e680, 0xc0029d83e0}, 0xc002d0dd40)\n\tgithub.com/traefik/traefik/v2/pkg/middlewares/accesslog/field_middleware.go:55 +0x1a2\ngithub.com/traefik/traefik/v2/pkg/middlewares/accesslog.(*FieldHandler).ServeHTTP(0xc0008b9740, {0x7fd0453bb250, 0xc000e7ef68}, 0xc0013d0280)\n\tgithub.com/traefik/traefik/v2/pkg/middlewares/accesslog/field_middleware.go:36 +0xd8\ngithub.com/traefik/traefik/v2/pkg/middlewares/metrics.(*metricsMiddleware).ServeHTTP(0xc0059d6070, {0x7fd0453bb200, 0xc000e7ef60}, 0xc000a51a00)\n\tgithub.com/traefik/traefik/v2/pkg/middlewares/metrics/metrics.go:121 +0x722\ngithub.com/traefik/traefik/v2/pkg/middlewares/tracing.(*entryPointMiddleware).ServeHTTP(0xc003231140, {0x7fd0453bb170, 0xc000e7ef48}, 0xc000a51800)\n\tgithub.com/traefik/traefik/v2/pkg/middlewares/tracing/entrypoint.go:52 +0x6e2\ngithub.com/traefik/traefik/v2/pkg/middlewares/accesslog.(*Handler).ServeHTTP(0xc003c25500, {0x3faf0f8, 0xc005ffe700}, 0xc000a51700, {0x3f6e7e0, 0xc003231140})\n\tgithub.com/traefik/traefik/v2/pkg/middlewares/accesslog/logger.go:227 +0xfa3\ncreated by net/http.(*Server).Serve\n\tnet/http/server.go:3034 +0x4e8\n","time":"2022-05-30T09:49:39Z"}
```

**Comment by yongzhang** [comment]
> > Træfik < 2.6 is supported only because they introduced some breaking changes.
> 
> ah, ok, thanks for letting me know.

@darkweak I see it supports traefik v3 now, does it support traefik v2.6+?

**Comment by darkweak** [comment]
Hey @yongzhang I didn't try with Træfik v2.6+ yet but I think it should work.
