### ISSUE TITLE
 Caddy 2.5.2 - invalid memory address or nil pointer dereference - 1.6.19

### ISSUE THREAD

**Issue by mattvb91** [darkweak/souin#252]
1.6.19 results in a invalid memory exception with the following post:

```
(*Configuration).SetLogger(...)\n\tgithub.com/darkweak/souin/plugins/caddy
```

See full log below

```bash
curl --location --request POST 'localhost:2019/load' \
--header 'Host: localhost' \
--header 'Content-Type: application/json' \
--data-raw '{
   "admin":{
      "disabled":false,
      "listen":":2019"
   },
   "apps":{
      "cache":{
         "api":{
            "basepath":"\/cache",
            "souin":{
               "basepath":"\/souin",
               "enable":true
            }
         },
         "cdn":{
            "dynamic":true,
            "strategy":"hard"
         },
         "log_level":"INFO",
         "stale":"3600s",
         "ttl":"3600s",
         "nuts":{
            "path":"\/tmp\/nuts-souin"
         }
      },
      "http":{
         "servers":{
            "cacheServer":{
               "listen":[
                  ":80"
               ],
               "routes":[
                  {
                     "handle":[
                        {
                           "handler":"cache"
                        },
                        {
                           "handler":"static_response",
                           "status_code":200,
                           "body":"cache test"
                        }
                     ]
                  }
               ]
            }
         }
      }
   }
}'
```

```
caddy_1     | {"level":"info","ts":1663672388.145363,"msg":"http: panic serving 172.19.0.1:39046: runtime error: invalid memory address or nil pointer dereference\ngoroutine 776 [running]:\nnet/http.(*conn).serve.func1()\n\tnet/http/server.go:1825 +0xbf\npanic({0x1c1ece0, 0x3166bd0})\n\truntime/panic.go:844 +0x258\ngithub.com/darkweak/souin/plugins/caddy.(*Configuration).SetLogger(...)\n\tgithub.com/darkweak/souin/plugins/caddy@v0.0.0-20220920094537-b444c3dcf946/configuration.go:148\ngithub.com/darkweak/souin/plugins/caddy.(*SouinCaddyPlugin).Provision(0xc0000005a0, {{0x229f060, 0xc00061cc80}, 0xc000753f20, 0xc0000a6550, {0x0, 0x0, 0x0}})\n\tgithub.com/darkweak/souin/plugins/caddy@v0.0.0-20220920094537-b444c3dcf946/httpcache.go:270 +0xc9\ngithub.com/caddyserver/caddy/v2.Context.LoadModuleByID({{0x229f060, 0xc00061cc80}, 0xc000753f20, 0xc0000a6550, {0x0, 0x0, 0x0}}, {0xc00032a3c0, 0x13}, {0xc000674140, ...})\n\tgithub.com/caddyserver/caddy/v2@v2.5.2/context.go:344 +0x3ff\ngithub.com/caddyserver/caddy/v2.Context.loadModuleInline({{0x229f060, 0xc00061cc80}, 0xc000753f20, 0xc0000a6550, {0x0, 0x0, 0x0}}, {0x1bf0840?, 0x0?}, {0x1bf0827, ...}, ...)\n\tgithub.com/caddyserver/caddy/v2@v2.5.2/context.go:394 +0x145\ngithub.com/caddyserver/caddy/v2.Context.LoadModule({{0x229f060, 0xc00061cc80}, 0xc000753f20, 0xc0000a6550, {0x0, 0x0, 0x0}}, {0x1bdee20, 0xc0002cb8c0}, {0x1ed47ad, ...})\n\tgithub.com/caddyserver/caddy/v2@v2.5.2/context.go:175 +0xdac\ngithub.com/caddyserver/caddy/v2/modules/caddyhttp.RouteList.ProvisionHandlers({0xc0002cb8c0, 0x1, 0xc0006ca860?}, {{0x229f060, 0xc00061cc80}, 0xc000753f20, 0xc0000a6550, {0x0, 0x0, 0x0}})\n\tgithub.com/caddyserver/caddy/v2@v2.5.2/modules/caddyhttp/routes.go:150 +0xcc\ngithub.com/caddyserver/caddy/v2/modules/caddyhttp.(*App).Provision(0xc0005dcc60, {{0x229f060, 0xc00061cc80}, 0xc000753f20, 0xc0000a6550, {0x0, 0x0, 0x0}})\n\tgithub.com/caddyserver/caddy/v2@v2.5.2/modules/caddyhttp/app.go:233 +0x925\ngithub.com/caddyserver/caddy/v2.Context.LoadModuleByID({{0x229f060, 0xc00061cc80}, 0xc000753f20, 0xc0000a6550, {0x0, 0x0, 0x0}}, {0xc000055b8c, 0x4}, {0xc0007ac0a0, ...})\n\tgithub.com/caddyserver/caddy/v2@v2.5.2/context.go:344 +0x3ff\ngithub.com/caddyserver/caddy/v2.Context.App({{0x229f060, 0xc00061cc80}, 0xc000753f20, 0xc0000a6550, {0x0, 0x0, 0x0}}, {0xc000055b8c, 0x4})\n\tgithub.com/caddyserver/caddy/v2@v2.5.2/context.go:415 +0x14f\ngithub.com/caddyserver/caddy/v2.run.func3(...)\n\tgithub.com/caddyserver/caddy/v2@v2.5.2/caddy.go:462\ngithub.com/caddyserver/caddy/v2.run(0xc0006a4540?, 0x1)\n\tgithub.com/caddyserver/caddy/v2@v2.5.2/caddy.go:467 +0x498\ngithub.com/caddyserver/caddy/v2.unsyncedDecodeAndRun({0xc0006a4380, 0x1aa, 0x1c0}, 0x1)\n\tgithub.com/caddyserver/caddy/v2@v2.5.2/caddy.go:322 +0x112\ngithub.com/caddyserver/caddy/v2.changeConfig({0x1eae211, 0x4}, {0x1eb9af8, 0x7}, {0xc0009f8000, 0x458, 0x600}, {0x0, 0x0}, 0x0)\n\tgithub.com/caddyserver/caddy/v2@v2.5.2/caddy.go:213 +0x79a\ngithub.com/caddyserver/caddy/v2.Load({0xc0009f8000, 0x458, 0x600}, 0x58?)\n\tgithub.com/caddyserver/caddy/v2@v2.5.2/caddy.go:115 +0x21c\ngithub.com/caddyserver/caddy/v2/caddyconfig.adminLoad.handleLoad({}, {0x22986b0, 0xc000a04438}, 0xc000684200)\n\tgithub.com/caddyserver/caddy/v2@v2.5.2/caddyconfig/load.go:116 +0x525\ngithub.com/caddyserver/caddy/v2.AdminHandlerFunc.ServeHTTP(0x5?, {0x22986b0?, 0xc000a04438?}, 0x6f6da0?)\n\tgithub.com/caddyserver/caddy/v2@v2.5.2/admin.go:1229 +0x2f\ngithub.com/caddyserver/caddy/v2.(*AdminConfig).newAdminHandler.func2.1({0x22986b0, 0xc000a04438}, 0xc000684200)\n\tgithub.com/caddyserver/caddy/v2@v2.5.2/admin.go:223 +0x87\nnet/http.HandlerFunc.ServeHTTP(0xc00061c000?, {0x22986b0?, 0xc000a04438?}, 0x1c9c9c0?)\n\tnet/http/server.go:2084 +0x2f\ngithub.com/caddyserver/caddy/v2.instrumentHandlerCounter.func1({0x229d660?, 0xc0009160e0}, 0xc000684200)\n\tgithub.com/caddyserver/caddy/v2@v2.5.2/metrics.go:46 +0xbc\nnet/http.HandlerFunc.ServeHTTP(0xc0009e03d0?, {0x229d660?, 0xc0009160e0?}, 0x67b305?)\n\tnet/http/server.go:2084 +0x2f\nnet/http.(*ServeMux).ServeHTTP(0x0?, {0x229d660, 0xc0009160e0}, 0xc000684200)\n\tnet/http/server.go:2462 +0x149\ngithub.com/caddyserver/caddy/v2.adminHandler.serveHTTP({0xc00061c000, 0x0, 0x0, {0xc0007ae010, 0x1, 0x1}, 0x0}, {0x229d660, 0xc0009160e0}, 0xc000684200)\n\tgithub.com/caddyserver/caddy/v2@v2.5.2/admin.go:789 +0x532\ngithub.com/caddyserver/caddy/v2.adminHandler.ServeHTTP({0xc00061c000, 0x0, 0x0, {0xc0007ae010, 0x1, 0x1}, 0x0}, {0x229d660, 0xc0009160e0}, 0xc000684200)\n\tgithub.com/caddyserver/caddy/v2@v2.5.2/admin.go:741 +0x7fe\nnet/http.serverHandler.ServeHTTP({0x2296c98?}, {0x229d660, 0xc0009160e0}, 0xc000684200)\n\tnet/http/server.go:2916 +0x43b\nnet/http.(*conn).serve(0xc00018c140, {0x229f108, 0xc000135b60})\n\tnet/http/server.go:1966 +0x5d7\ncreated by net/http.(*Server).Serve\n\tnet/http/server.go:3071 +0x4db"}

```

**Comment by darkweak** [comment]
There is no logger in the configuration

**Comment by mattvb91** [comment]
hmm, I wonder if thats a regression from caddy 2.5.1 -> 2.5.2 then and not relevant here cause on the old versions it works with that config posted above: https://github.com/mattvb91/caddy-php/actions/runs/3089774893/jobs/4997767762#step:5:306
