### ISSUE TITLE
404 causes invalid memory address or nil pointer dereference - NutsDB - Souin 1.6.22

### ISSUE THREAD

**Issue by mattvb91** [darkweak/souin#261]
Fetching a resource that doesnt exists 'missing.js' causes a complete crash of caddy / souin on the latest tag

```
caddy_1                | {"level":"debug","ts":1665914150.4616704,"logger":"http.handlers.cache","msg":"Incoming request: &{Method:GET URL:/missing.js Proto:HTTP/1.1 ProtoMajor:1 ProtoMinor:1 Header:map[Accept:[*/*] Accept-Encoding:[gzip] Accept-Language:[en-US,en;q=0.9] Cache-Control:[max-age=0] Connection:[keep-alive] Date:[Sun, 16 Oct 2022 09:55:50 UTC] Proxy-Connection:[keep-alive] Referer:[http://localhost/missing.js] Sec-Fetch-Dest:[serviceworker] Sec-Fetch-Mode:[same-origin] Sec-Fetch-Site:[same-origin] Service-Worker:[script] User-Agent:[Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36]] Body:{} GetBody:<nil> ContentLength:0 TransferEncoding:[] Close:false Host:localhost Form:map[] PostForm:map[] MultipartForm:<nil> Trailer:map[] RemoteAddr:172.18.0.1:46930 RequestURI:/missing.js TLS:<nil> Cancel:<nil> Response:<nil> ctx:0xc003f4c630}"}
caddy_1                | panic: runtime error: invalid memory address or nil pointer dereference
caddy_1                | [signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x1be7418]
caddy_1                | 
caddy_1                | goroutine 917 [running]:
caddy_1                | github.com/xujiajun/nutsdb.(*Tx).getTxID(0x1200c000714160?)
caddy_1                |        github.com/xujiajun/nutsdb@v0.9.0/tx.go:123 +0x18
caddy_1                | github.com/xujiajun/nutsdb.newTx(0x0, 0x0)
caddy_1                |        github.com/xujiajun/nutsdb@v0.9.0/tx.go:111 +0x9f
caddy_1                | github.com/xujiajun/nutsdb.(*DB).Begin(0x0, 0xd8?)
caddy_1                |        github.com/xujiajun/nutsdb@v0.9.0/tx.go:85 +0x25
caddy_1                | github.com/xujiajun/nutsdb.(*DB).managed(0xc003f4c720?, 0x1?, 0xc0002f7bf8)
caddy_1                |        github.com/xujiajun/nutsdb@v0.9.0/db.go:958 +0x39
caddy_1                | github.com/xujiajun/nutsdb.(*DB).View(...)
caddy_1                |        github.com/xujiajun/nutsdb@v0.9.0/db.go:295
caddy_1                | github.com/darkweak/souin/cache/providers.(*Nuts).Prefix(0xc0002f7d88?, {0xc0002ac378?, 0xc0041840d0?}, 0xe?)
caddy_1                |        github.com/darkweak/souin@v1.6.22/cache/providers/nutsProvider.go:143 +0x72
caddy_1                | github.com/darkweak/souin/rfc.CachedResponse({0x268c8f8, 0xc00084a630}, 0xc004262900, {0xc0002ac378, 0x14}, {0xc0079e9e40?, 0x4d9565?})
caddy_1                |        github.com/darkweak/souin@v1.6.22/rfc/bridge.go:24 +0x1fb
caddy_1                | github.com/darkweak/souin/plugins.DefaultSouinPluginCallback.func1(0x70?, {0x26904b0, 0xc0009ee000}, {0xc0002ac378, 0x14})
caddy_1                |        github.com/darkweak/souin@v1.6.22/plugins/base.go:145 +0xf8
caddy_1                | created by github.com/darkweak/souin/plugins.DefaultSouinPluginCallback
caddy_1                |        github.com/darkweak/souin@v1.6.22/plugins/base.go:143 +0x4e5

```

**Comment by mattvb91** [comment]
Sorry looks like this is the same issue as #256 i didnt realise it was closed and thought I hadn't opened an issue yet. So the issue existed on that version too

**Comment by mattvb91** [comment]
Just as reference for anyone else, tried it with the latest release https://github.com/darkweak/souin/releases/tag/v1.6.27 and still the same:

```
caddy_1  | panic: runtime error: invalid memory address or nil pointer dereference
caddy_1  | [signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x1d60338]
caddy_1  | 
caddy_1  | goroutine 122 [running]:
caddy_1  | github.com/xujiajun/nutsdb.(*Tx).getTxID(0xc000370000?)
caddy_1  |      github.com/xujiajun/nutsdb@v0.11.1/tx.go:123 +0x18
caddy_1  | github.com/xujiajun/nutsdb.newTx(0x0, 0x0)
caddy_1  |      github.com/xujiajun/nutsdb@v0.11.1/tx.go:111 +0x9f
caddy_1  | github.com/xujiajun/nutsdb.(*DB).Begin(0x0, 0x60?)
caddy_1  |      github.com/xujiajun/nutsdb@v0.11.1/tx.go:85 +0x25
caddy_1  | github.com/xujiajun/nutsdb.(*DB).managed(0x21da180?, 0x1?, 0xc000230bf8)
caddy_1  |      github.com/xujiajun/nutsdb@v0.11.1/db.go:978 +0x39
caddy_1  | github.com/xujiajun/nutsdb.(*DB).View(...)

```

**Comment by darkweak** [comment]
Can you retry with the latest release @mattvb91? 🙏

**Comment by darkweak** [comment]
Did you remove the nutsdb storage folder? `/tmp/souin-nuts` by default.

**Comment by mattvb91** [comment]
yup

**Comment by darkweak** [comment]
Can you paste your `Caddyfile`/`configuration.json` file please?
How do you build your caddy binary?
Can you paste all steps/commands you're running to build/start caddy?

**Comment by darkweak** [comment]
ping @mattvb91

**Comment by mattvb91** [comment]
With latest release from today:

Caddy config:

```json
{
   "admin":{
      "disabled":false,
      "listen":":2019"
   },
   "apps":{
      "cache":{
         "api":{
            "basepath":"/cache",
            "souin":{
               "basepath":"/souin",
               "enable":true
            }
         },
         "cache_keys":{
            "/_next\\/static/":{
               "disable_body":false,
               "disable_host":true,
               "disable_method":false
            }
         },
         "cdn":{
            "dynamic":true,
            "strategy":"hard"
         },
         "log_level":"DEBUG",
         "nuts":{
            "path":"/tmp/nuts-souin"
         },
         "stale":"0s",
         "ttl":"3600s"
      },
      "http":{
         "servers":{
            "platform":{
               "listen":[
                  ":80"
               ],
               "routes":[
                  {
                     "handle":[
                        {
                           "handler":"subroute",
                           "routes":[
                              
                           ]
                        },
                        {
                           "handler":"subroute",
                           "routes":[
                              {
                                 "handle":[
                                    {
                                       "allowed_http_verbs":[
                                          "GET"
                                       ],
                                       "default_cache_control":"no-store",
                                       "handler":"cache",
                                       "log_level":"DEBUG"
                                    },
                                    {
                                       "handler":"reverse_proxy",
                                       "upstreams":[
                                          {
                                             "dial":"nextjs-shop:3000"
                                          }
                                       ]
                                    }
                                 ],
                                 "match":[
                                    {
                                       "path":[
                                          "/_next/static/*",
                                          "/favicon*",
                                          "/site.webmanifest",
                                          "/robots.txt"
                                       ]
                                    }
                                 ]
                              }
                           ]
                        },
                        {
                           "handler":"subroute",
                           "routes":[
                              {
                                 "handle":[
                                    {
                                       "handler":"headers",
                                       "request":{
                                          "delete":[
                                             "cache-control",
                                             "pragma"
                                          ]
                                       },
                                       "response":{
                                          "deferred":true,
                                          "delete":[
                                             "server",
                                             "x-powered-by"
                                          ]
                                       }
                                    },
                                    {
                                       "allowed_http_verbs":[
                                          "GET"
                                       ],
                                       "default_cache_control":"no-store",
                                       "handler":"cache",
                                       "log_level":"DEBUG"
                                    },
                                    {
                                       "handler":"reverse_proxy",
                                       "transport":{
                                          "protocol":"fastcgi",
                                          "root":"/app/public/index.php",
                                          "split_path":[
                                             ""
                                          ]
                                       },
                                       "upstreams":[
                                          {
                                             "dial":"laravel-api:9000"
                                          }
                                       ]
                                    }
                                 ],
                                 "match":[
                                    {
                                       "path":[
                                          "/api/shop/image/*"
                                       ]
                                    }
                                 ]
                              }
                           ]
                        },
                        {
                           "handler":"headers",
                           "request":{
                              "delete":[
                                 "cache-control",
                                 "pragma"
                              ]
                           },
                           "response":{
                              "deferred":true,
                              "delete":[
                                 "cache-control",
                                 "pragma",
                                 "server",
                                 "x-powered-by"
                              ]
                           }
                        },
                        {
                           "allowed_http_verbs":[
                              "GET"
                           ],
                           "default_cache_control":"no-store",
                           "handler":"cache",
                           "log_level":"DEBUG"
                        },
                        {
                           "handler":"subroute",
                           "routes":[
                              {
                                 "handle":[
                                    {
                                       "allowed_http_verbs":[
                                          "GET"
                                       ],
                                       "default_cache_control":"no-store",
                                       "handler":"cache",
                                       "log_level":"DEBUG"
                                    },
                                    {
                                       "handler":"reverse_proxy",
                                       "transport":{
                                          "protocol":"fastcgi",
                                          "root":"/app/public/index.php",
                                          "split_path":[
                                             ""
                                          ]
                                       },
                                       "upstreams":[
                                          {
                                             "dial":"laravel-api:9000"
                                          }
                                       ]
                                    }
                                 ],
                                 "match":[
                                    {
                                       "not":[
                                          {
                                             "path":[
                                                "/api/shop/image/*"
                                             ]
                                          }
                                       ],
                                       "path":[
                                          "/api/*"
                                       ]
                                    }
                                 ]
                              },
                              {
                                 "handle":[
                                    {
                                       "handler":"reverse_proxy",
                                       "upstreams":[
                                          {
                                             "dial":"nextjs-shop:3000"
                                          }
                                       ]
                                    }
                                 ],
                                 "match":[
                                    {
                                       "not":[
                                          {
                                             "path":[
                                                "/favicon/sources/placeholder",
                                                "/_next/js/*",
                                                "/_next/static/*"
                                             ]
                                          }
                                       ]
                                    }
                                 ]
                              }
                           ]
                        }
                     ],
                     "match":[
                        {
                           "host":[
                              "test.localhost",
                              "random-knv95sm6.localhost"
                           ]
                        }
                     ],
                     "terminal":true
                  },
                  {
                     "handle":[
                        {
                           "handler":"subroute",
                           "routes":[
                              
                           ]
                        },
                        {
                           "allowed_http_verbs":[
                              "GET"
                           ],
                           "default_cache_control":"no-store",
                           "handler":"cache",
                           "log_level":"DEBUG"
                        },
                        {
                           "handler":"subroute",
                           "routes":[
                              {
                                 "handle":[
                                    {
                                       "handler":"rewrite",
                                       "strip_path_prefix":"/_next/js"
                                    }
                                 ],
                                 "match":[
                                    {
                                       "path":[
                                          "/_next/js/*"
                                       ]
                                    }
                                 ]
                              },
                              {
                                 "handle":[
                                    {
                                       "allowed_http_verbs":[
                                          "GET"
                                       ],
                                       "default_cache_control":"no-store",
                                       "handler":"cache",
                                       "log_level":"DEBUG"
                                    },
                                    {
                                       "handler":"reverse_proxy",
                                       "transport":{
                                          "protocol":"fastcgi",
                                          "root":"/app/public/index.php",
                                          "split_path":[
                                             ""
                                          ]
                                       },
                                       "upstreams":[
                                          {
                                             "dial":"laravel-api:9000"
                                          }
                                       ]
                                    }
                                 ],
                                 "match":[
                                    {
                                       "path":[
                                          "/api/*"
                                       ]
                                    }
                                 ]
                              },
                              {
                                 "handle":[
                                    {
                                       "handler":"reverse_proxy",
                                       "upstreams":[
                                          {
                                             "dial":"nextjs-platform:3000"
                                          }
                                       ]
                                    }
                                 ]
                              }
                           ]
                        }
                     ],
                     "match":[
                        {
                           "host":[
                              "localhost"
                           ]
                        }
                     ],
                     "terminal":true
                  }
               ]
            }
         }
      }
   },
   "logging":{
      "logs":{
         "default":{
            "level":"DEBUG"
         }
      }
   }
}
```

Dockerfile `./docker/prod/caddy/Dockerfile`:

```
FROM caddy:2.6.4-builder-alpine

# Make sure souin is version locked and test everything before upgrades
# nutsdb with caddy is broken past souin v1.6.17
RUN xcaddy build --with github.com/caddy-dns/route53 \
    --with github.com/darkweak/souin/plugins/caddy@ca16a574707549a10e8cf0d74bcb84ed6872be45 \
    --with github.com/darkweak/souin@ca16a574707549a10e8cf0d74bcb84ed6872be45 \
    --with github.com/caddyserver/caddy/v2=github.com/caddyserver/caddy/v2@v2.6.4

RUN apk --no-cache --update add mailcap #mimetype support

# See https://caddyserver.com/docs/conventions#file-locations for details
ENV XDG_CONFIG_HOME /config
ENV XDG_DATA_HOME /data

VOLUME /config
VOLUME /data


EXPOSE 80
EXPOSE 443
EXPOSE 2019

WORKDIR /srv

```

Then in `docker-compose.yml`

```
  caddy:
    build:
      context: ./docker/prod/caddy
    restart: unless-stopped
    depends_on:
      - laravel-api
      - nextjs-platform
      - nextjs-shop
    command: [ "caddy", "run", "--resume" ]
    ports:
      - "80:80" 
      - "443:443"
      - "2019:2019"
    volumes:
      - ./docker/dev/caddy/caddy_data:/data
      - ./docker/dev/caddy/caddy_config:/config
      - ./backend:/app
      - ./backend/storage/static:/assets
```

and its just a `docker-compose up -d`. But none of that should have anything to do with `nutsdb` as that happens inside the container.

**Comment by darkweak** [comment]
Do you have a curl request that fails?

**Comment by darkweak** [comment]
@mattvb91 I investigated on that, I really think that's a permission issue. You should see an error log during Souin initialization that contains `Impossible to open the Nuts DB.`.  
I am able to reproduce your panic with the snippet below, and as the Nuts provider init is failing silently that's why it doesn't panic at startup and only show an error log.  
Either the caddy process in your container doesn't have enough rights to write in the `/tmp` folder or the error comes from the nuts library itself because the only way the NutsProvider.db property could be nil is when we assign the returned value from `nutsdb.Open`.
This permission issue could explain why @kresike and I couldn't reproduce that behavior.

```go
package main

import (
	"fmt"

	"github.com/xujiajun/nutsdb"
)

func main() {
	nutsOptions := nutsdb.DefaultOptions
	// mkdir /tmp/souin-nuts && chmod -R 555 /tmp/souin-nuts
	nutsOptions.Dir = "/tmp/souin-nuts"

	db, err := nutsdb.Open(nutsOptions)
	if err != nil {
		panic(err)
	}

	var result []byte

	_ = db.View(func(tx *nutsdb.Tx) error {
		prefix := []byte("my-key")

		if _, _, err := tx.PrefixSearchScan("souin-bucket", prefix, "^({|$)", 0, 50); err != nil {
			return err
		}

		result = []byte("Hello world")

		return nil
	})

	fmt.Println("Result =>", result)
}
```

**Comment by mattvb91** [comment]
> Do you have a curl request that fails?

Every request after a certain while, it looks like its the corruption thing again. Does souin / nutsdb not create the initial tmp file in the first place with whatever permission are needed? What chmod should I include in the dockerfile? Even when caddy runs as root it still errors?

```bash
curl 'http://localhost/favicon.ico' \
  -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7' \
  -H 'Accept-Language: en,de;q=0.9,en-IE;q=0.8,en-US;q=0.7' \
  -H 'Cache-Control: no-cache' \
  -H 'Connection: keep-alive' \
  -H 'Pragma: no-cache' \
  -H 'Sec-Fetch-Dest: document' \
  -H 'Sec-Fetch-Mode: navigate' \
  -H 'Sec-Fetch-Site: none' \
  -H 'Sec-Fetch-User: ?1' \
  -H 'Upgrade-Insecure-Requests: 1' \
  -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36' \
  -H 'sec-ch-ua: "Chromium";v="110", "Not A(Brand";v="24", "Google Chrome";v="110"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "Linux"' \
  --compressed


curl: (52) Empty reply from server

```

**Comment by darkweak** [comment]
Can you try to chmod as `777` to exclude the permission hypothesis. If that doesn't solve, can you try to decrease the nutsdb memory allocation using the configuration directive?

**Comment by mattvb91** [comment]
No luck with 777. But as you mentioned above I am seeing 

```
caddy_1  | {"level":"error","ts":1678871795.960698,"logger":"http.handlers.cache","msg":"Impossible to open the Nuts DB.db.buildIndexes error: when build activeDataIndex readAt err: crc error"}
```

Which would obviously explain the invalid memory error. 

However the file is there and it is created by the caddy process. So im not sure why ownership could be wrong or why its not able to access it. Souin is the one creating the file.

`v.1.6.17` opens & writes to the file with no issues.

If I try and set the `configuration` directive it doesnt create any tmp file at all (However it returns cache hits) so im assuming its just the memory (badger) instance thats caching? 

```
"nuts": {
"configuration": {
"SegmentSize": "20MB"
},
"path": "[/tmp/nuts-souin](http://localhost:2019/tmp/nuts-souin)"
},
```

**Comment by darkweak** [comment]
If you run Souin as caddy module with debug log level for caddy, and if you see in the logs something like that
```
2023/03/15 11:34:38.894 DEBUG   http.handlers.cache     writeRequests called. Writing to value log
2023/03/15 11:34:38.894 DEBUG   http.handlers.cache     Sending updates to subscribers
2023/03/15 11:34:38.894 DEBUG   http.handlers.cache     Writing to memtable
2023/03/15 11:34:38.894 DEBUG   http.handlers.cache     2 entries written
2023/03/15 11:34:38.894 DEBUG   http.handlers.cache     writeRequests called. Writing to value log
2023/03/15 11:34:38.894 DEBUG   http.handlers.cache     Sending updates to subscribers
2023/03/15 11:34:38.894 DEBUG   http.handlers.cache     Writing to memtable
2023/03/15 11:34:38.894 DEBUG   http.handlers.cache     2 entries written
```
That means badger is used to store the data, nuts otherwise.

**Comment by darkweak** [comment]
@mattvb91 Did you have time to test that? 
Given the following configuration
```
"nuts": {
  "configuration": {
    "Dir": "/tmp/nuts-souin",
    "SegmentSize": "20MB"
  }
},
```
If you want to override the directory from the `configuration` directive you have to use the Dir option. The `path` directive is used only if the configuration directive is not filled.

**Comment by mattvb91** [comment]
Still the same even with your directives above. On the latest release from today:

```
caddy_1  | {"level":"debug","ts":1682502041.3760545,"logger":"http.stdlib","msg":"http: panic serving 172.23.0.1:44552: runtime error: invalid memory address or nil pointer dereference\ngoroutine 778 [running]:\nnet/http.(*conn).serve.func1()\n\tnet/http/server.go:1850 +0xbf\npanic({0x1f18d60, 0x37e5f10})\n\truntime/panic.go:890 +0x262\ngithub.com/xujiajun/nutsdb.(*Tx).getTxID(0x0?)\n\tgithub.com/xujiajun/nutsdb@v0.11.1/tx.go:123 +0x18\ngithub.com/xujiajun/nutsdb.newTx(0x0, 0x0)\n\tgithub.com/xujiajun/nutsdb@v0.11.1/tx.go:111 +0x9f\ngithub.com/xujiajun/nutsdb.(*DB).Begin(0x0, 0x8?)\n\tgithub.com/xujiajun/nutsdb@v0.11.1/tx.go:85 +0x25\ngithub.com/xujiajun/nutsdb.(*DB).managed(0xc000df6b00?, 0xbc?, 0xc000df6ad0)\n\tgithub.com/xujiajun/nutsdb@v0.11.1/db.go:978 +0x39\ngithub.com/xujiajun/nutsdb.(*DB).View(...)\n\tgithub.com/xujiajun/nutsdb@v0.11.1/db.go:307\ngithub.com/darkweak/souin/pkg/storage.(*Nuts).Prefix(0xc000bdf200?, {0xc0001188d0?, 0x0?}, 0xc000df6da8?, 0x66755c64666666ff?)\n\tgithub.com/darkweak/souin@v1.6.38/pkg/storage/nutsProvider.go:145 +0x6d\ngithub.com/darkweak/souin/pkg/middleware.(*SouinBaseHandler).ServeHTTP(0xc0001fb180, {0x279d6d0, 0xc00105ad20}, 0xc000bdeb00, 0xc00030db60)\n\tgithub.com/darkweak/souin@v1.6.38/pkg/middleware/middleware.go:377 +0x838\ngithub.com/darkweak/souin/plugins/caddy.(*SouinCaddyMiddleware).ServeHTTP(0xc000781a40, {0x279d6d0, 0xc00105ad20}, 0xc000bdeb00, {0x278b680?, 0xc0005179b0})\n\tgithub.com/darkweak/souin/plugins/caddy@v0.0.0-20230426055538-2577ef696657/httpcache.go:82 +0xb3\ngithub.com/caddyserver/caddy/v2/modules/caddyhttp.wrapMiddleware.func1.1({0x279d6d0?, 0xc00105ad20?}, 0xc000620ea0?)\n\tgithub.com/caddyserver/caddy/v2@v2.6.4/modules/caddyhttp/routes.go:290 +0x42\ngithub.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0x1ef9720?, {0x279d6d0?, 0xc00105ad20?}, 0xe?)\n\tgithub.com/caddyserver/caddy/v2@v2.6.4/modules/caddyhttp/caddyhttp.go:58 +0x2f\ngithub.com/caddyserver/caddy/v2/modules/caddyhttp.wrapRoute.func1.1({0x279d6d0, 0xc00105ad20}, 0xc000bdeb00)\n\tgithub.com/caddyserver/caddy/v2@v2.6.4/modules/caddyhttp/routes.go:227 +0x336\ngithub.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0xc000c11680?, {0x279d6d0?, 0xc00105ad20?}, 0x278b680?)\n\tgithub.com/caddyserver/caddy/v2@v2.6.4/modules/caddyhttp/caddyhttp.go:58 +0x2f\ngithub.com/caddyserver/caddy/v2/modules/caddyhttp.(*Subroute).ServeHTTP(0xc00098a760, {0x279d6d0, 0xc00105ad20}, 0x1e49e01?, {0x278b680, 0xc0005179e0})\n\tgithub.com/caddyserver/caddy/v2@v2.6.4/modules/caddyhttp/subroute.go:74 +0x6d\ngithub.com/caddyserver/caddy/v2/modules/caddyhttp.wrapMiddleware.func1.1({0x279d6d0?, 0xc00105ad20?}, 0x278b680?)\n\tgithub.com/caddyserver/caddy/v2@v2.6.4/modules/caddyhttp/routes.go:290 +0x42\ngithub.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0x278b680?, {0x279d6d0?, 0xc00105ad20?}, 0xc0001f9e40?)\n\tgithub.com/caddyserver/caddy/v2@v2.6.4/modules/caddyhttp/caddyhttp.go:58 +0x2f\ngithub.com/caddyserver/caddy/v2/modules/caddyhttp.wrapRoute.func1.1({0x279d6d0, 0xc00105ad20}, 0xc000bdeb00)\n\tgithub.com/caddyserver/caddy/v2@v2.6.4/modules/caddyhttp/routes.go:259 +0x3a8\ngithub.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0x1ef9720?, {0x279d6d0?, 0xc00105ad20?}, 0xe?)\n\tgithub.com/caddyserver/caddy/v2@v2.6.4/modules/caddyhttp/caddyhttp.go:58 +0x2f\ngithub.com/caddyserver/caddy/v2/modules/caddyhttp.wrapRoute.func1.1({0x279d6d0, 0xc00105ad20}, 0xc000bdeb00)\n\tgithub.com/caddyserver/caddy/v2@v2.6.4/modules/caddyhttp/routes.go:227 +0x336\ngithub.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0x1500?, {0x279d6d0?, 0xc00105ad20?}, 0x212c120?)\n\tgithub.com/caddyserver/caddy/v2@v2.6.4/modules/caddyhttp/caddyhttp.go:58 +0x2f\ngithub.com/caddyserver/caddy/v2/modules/caddyhttp.(*Server).enforcementHandler(0x0?, {0x279d6d0?, 0xc00105ad20?}, 0xc000514af0?, {0x278b680?, 0xc00098bd40?})\n\tgithub.com/caddyserver/caddy/v2@v2.6.4/modules/caddyhttp/server.go:388 +0x252\ngithub.com/caddyserver/caddy/v2/modules/caddyhttp.(*Server).wrapPrimaryRoute.func1({0x279d6d0?, 0xc00105ad20?}, 0x4cb117?)\n\tgithub.com/caddyserver/caddy/v2@v2.6.4/modules/caddyhttp/server.go:364 +0x3b\ngithub.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0xc000543040?, {0x279d6d0?, 0xc00105ad20?}, 0xc000bdeb00?)\n\tgithub.com/caddyserver/caddy/v2@v2.6.4/modules/caddyhttp/caddyhttp.go:58 +0x2f\ngithub.com/caddyserver/caddy/v2/modules/caddyhttp.(*Server).ServeHTTP(0xc000207900, {0x279d6d0, 0xc00105ad20}, 0xc000bdeb00)\n\tgithub.com/caddyserver/caddy/v2@v2.6.4/modules/caddyhttp/server.go:300 +0xb66\nnet/http.serverHandler.ServeHTTP({0xc0005176b0?}, {0x279d6d0, 0xc00105ad20}, 0xc000bde900)\n\tnet/http/server.go:2947 +0x30c\nnet/http.(*conn).serve(0xc0004cefa0, {0x279f510, 0xc000856630})\n\tnet/http/server.go:1991 +0x607\ncreated by net/http.(*Server).Serve\n\tnet/http/server.go:3102 +0x4db"}
```

**Comment by darkweak** [comment]
Cannot reproduce anymore at the moment with the `v1.6.43`.
